Import("env")   # scons? Claude output
import os

pioenv = env["PIOENV"]
src_file = f"bring-up/{pioenv}.c"
src_path = os.path.join(env["PROJECT_DIR"], "src", src_file)

if not os.path.isfile(src_path):
    raise SystemExit(f"[bring-up] Expected source file not found: {src_path}")

cmakelists_path = os.path.join(env["PROJECT_DIR"], "src", "CMakeLists.txt")
content = f'''# AUTO-GENERATED by generate_bringup.py — do not edit by hand
idf_component_register(
    SRCS "{src_file}"
    INCLUDE_DIRS "."
)
'''

# only rewrite if changed, to avoid needless cache invalidation
existing = ""
if os.path.isfile(cmakelists_path):
    with open(cmakelists_path) as f:
        existing = f.read()

if existing != content:
    with open(cmakelists_path, "w") as f:
        f.write(content)
    print(f"[bring-up] src/CMakeLists.txt -> {src_file}")