Import("env")   # scons? Claude output
import os

pioenv = env["PIOENV"]
src_dir = os.path.join(env["PROJECT_DIR"], "src") 

# get all .cpp files for main
if pioenv == "main":
    src_files = [file for file in os.listdir(src_dir) if file.endswith(".cpp")]

# get only the singular C file for that bring up test
else:
    src_files = [f"{src_dir}/bring-up/{pioenv}.c"]


if not all([lambda file=file: os.path.isfile(file) for file in src_files]):
    raise SystemExit(f"[bring-up] Expected source files not found: {src_files}")

srcs_str = ' '.join([f'"{src}"' for src in src_files]) 

cmakelists_path = os.path.join(env["PROJECT_DIR"], "src", "CMakeLists.txt")
content = f'''# AUTO-GENERATED by generate_bringup.py — do not edit by hand

idf_component_register(
    SRCS {srcs_str}
    REQUIRES esp_timer
    INCLUDE_DIRS "."
)

'''

# only rewrite if changed, to avoid needless cache invalidation
existing = ""
if os.path.isfile(cmakelists_path):
    with open(cmakelists_path) as f:
        existing = f.read()

if existing != content:
    with open(cmakelists_path, "w") as f:
        f.write(content)
    print(f"[bring-up] src/CMakeLists.txt -> {srcs_str}")